### ISSUE TITLE
Please publish this on crates.io

### ISSUE THREAD

**Issue by sebschmi** [Kmer-File-Format/kff-rust-api#1]
I just saw the paper you published about kff. Amazing work! We would like to use it in our research. To make it easy, could you publish this crate on crates.io?

**Comment by yoann-dufresne** [comment]
Hi @sebschmi, I'll chat with @natir about that.
Thanks for your kind message.

**Comment by natir** [comment]
Hi @sebschmi the actual version of rust parser isn't totaly, up to date (I hope I finish rewrite before the end of this month). When all feature are implemented rust kff parser will be publish on crates.io.

**Comment by sebschmi** [comment]
Alright, thank you for the quick reply!

**Comment by natir** [comment]
If you want follow progress to 1.0 you can check #2

**Comment by natir** [comment]
I publish a 0.9.0 version of KFF parser https://crates.io/crates/kff.

I am not totally satisfied with the API, I would need some time to think about it more.

But we have a first version, if you have any comments about the current API, don't hesitate. We still need to work on the examples and the documentation.

**Comment by sebschmi** [comment]
Cool! I will try integrating KFF into my tool in the next weeks. If I notice something, I will tell you.
