### ISSUE TITLE
Prevent duplication of data in a block?

### ISSUE THREAD

**Issue by lrobidou** [Kmer-File-Format/kff-rust-api#6]
I don't know if this is the correct place to discuss that, but I have one data for each block, not for each kmer. I currently duplicate the data for all kmers. Do I have a way to avoid that?

**Comment by natir** [comment]
Define a global data for block isn't possible for KFF.

But I think a good way to do this it's create a Values block before each Raw block with your value. You could reuse same key name each time, during read value is overwrite.
