### ISSUE TITLE
Forbid repetition of minimizer

### ISSUE THREAD

**Issue by lrobidou** [Kmer-File-Format/kff-rust-api#7]
I am storing non-unique kmers, but all kmers having the same minimizer are guaranteed to be grouped in a single minimizer section. This guarantee allows me to count the kmers without maintaining a large hashtable: once a minimizer is done, I can safely report the count of the kmers and empty the hashtable.

Do I have a way to communicate that guarantee to users? Or should I use the free section of the file format?

**Comment by yoann-dufresne** [comment]
For the KFF v1.0 you have to use the free section. If you can imagine better solutions, do not hesitate to ask for improvements in the following versions in the ref : https://github.com/Kmer-File-Format/kff-reference
