### ISSUE TITLE
docs: clashing license

### ISSUE THREAD

**Issue by lrobidou** [Kmer-File-Format/kff-rust-api#8]
The second sentence of this page of the doc  ( https://kmer-file-format.github.io/kff-rust-api/contributing.html ) is:
```
Keep in mind as you contribute, that code, docs and other material submitted to this projects are considered licensed under MIT license.
```
But the license file says the code's license is AGPL (I can open a PR to correct that but I don't know which one is true).

**Comment by natir** [comment]
Oups I make this error when I copy my template.
